config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: "departure_airport_id", class_name: "Airport"
  has_many :arriving_flights, foreign_key: "arrival_airport_id", class_name: "Airport"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Flight.find(params[:result_id]).bookings.new(num_passengers: params[:passenger_count])
    @booking.num_passengers.times do |i|
      @booking.passengers.build
    end
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking
    else
      flash.now[:error] = "Could not create booking."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @dates = Flight.pluck(:date)

    @results = Flight.where(search_params) if params.has_key?(:departure_airport)
    @passenger_count = params[:passenger_count]
  end

  private
  def search_params
    {departure_airport: Airport.find(params[:departure_airport]),
    arrival_airport: Airport.find(params[:arrival_airport]),
    date: params[:date]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= form_with model: @booking do |b| %>
  <p>Flight: <%= @booking.flight.id %></p>
  <p>Departing: <%= @booking.flight.departure_airport.code %></p>
  <p>Arriving: <%= @booking.flight.arrival_airport.code %></p>
  <p>Number of Passengers: <%= @booking.num_passengers %></p>
    <%= b.fields_for :passengers do |p| %>
      <p>Passenger</p>
      <div class="field">
        Name
        <%= p.text_field :name %>
      </div>
      <div class="field">
        Email
        <%= p.text_field :email %>
      </div>
    <% end %>
  <%= b.hidden_field :flight_id, value: @booking.flight.id %>
  <%= b.submit %>
<% end %>

app/views/bookings/show.html.erb
  <p>Flight: <%= @booking.flight.id %></p>
  <p>Departing: <%= @booking.flight.departure_airport.code %></p>
  <p>Arriving: <%= @booking.flight.arrival_airport.code %></p>
  <p>Number of Passengers: <%= @booking.num_passengers %></p>

  <p>Passengers:</p>
  <% @booking.passengers.each do |passenger| %>
    <div><%= passenger.name %></div>
  <% end %>

app/views/flights/index.html.erb
<h1>Flight Search</h1>

<%= form_with url: flights_path, method: :get do |form| %>
  <div class="field">
    <%= form.label :departure_airport %>
    <%= select_tag(:departure_airport, options_from_collection_for_select(@airports, :id, :code)) %>
  </div>
  <div class="field">
    <%= form.label :arrival_airport %>
    <%= select_tag(:arrival_airport, options_from_collection_for_select(@airports, :id, :code)) %>
  </div>
  <div class="field">
    <%= form.label :passenger_count %>
    <%= select_tag(:passenger_count, options_for_select(1..4)) %>
  </div>
  <div class="field">
    <%= form.label :date %>
    <%= select_tag(:date, options_for_select(@dates)) %>
  </div>
  <div class="field">
    <%= form.submit "Search", name: nil %>
  </div>
<% end %>

<% if @results.present? %>
<%= form_with url: new_booking_path, method: :get do |form| %>
  <div class="results">
    <table>
      <tr>
        <th>Select</th>
        <th>Flight #</th>
        <th>Departure Airport</th>
        <th>Arrival Airport</th>
        <th>Date</th>
      </tr>
      <% @results.each do |result| %>
      <tr>
        <td><%= form.radio_button :result_id, result.id %></td>
        <td><%= result.id %></td>
        <td><%= result.departure_airport.code %></td>
        <td><%= result.arrival_airport.code %></td>
        <td><%= result.date %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <%= form.hidden_field :passenger_count, value: @passenger_count %>
  <%= form.submit "Select", name: nil %>
<% end %>
<% else %>
  <p>No flights found.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>